index:
  path: /last-tweet
  controller: App\Controller\DefaultController::lastTweet

historical:
  path: /historical
  controller: App\Controller\DefaultController::historicalTweets

twitter-status:
  path: /status
  controller: App\Controller\DefaultController::status

analysis:
  path: /analysis
  controller: App\Controller\DefaultController::analysis

analysis-mention:
  path: /analysis/{mentionId}
  controller: App\Controller\DefaultController::analyseMention

graph:
  path: /graph
  controller: App\Controller\DefaultController::graph

api-tweet-count:
  path: /tweet-count/{year}
  controller: App\Controller\ApiController::tweetCount

api-tweet-count-month:
  path: /tweet-count/{year}/{month}
  controller: App\Controller\ApiController::tweetCount

api-tweet-count-day:
  path: /tweet-count/{year}/{month}/{day}
  controller: App\Controller\ApiController::tweetCount

api-tweet-count-hour:
  path: /tweet-count/{year}/{month}/{day}/{hour}
  controller: App\Controller\ApiController::tweetCount
